<?php
    include("include/config.php");
    // hardcode sidebar array
    $menu = array(

        'permissions' => array(
                            array(
                                'id' => "90",
                                'name' => "Business",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'businesses.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-briefcase",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "190",
                                'name' => "App User List",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'appUserListing.php',
                                'priority' => "2",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-users",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            // array(
                            //     'id' => "110",
                            //     'name' => "Purchase History",
                            //     'type' => "Menu",
                            //     'parent_id' => "0",
                            //     'file_path' => 'topUpHistory.php',
                            //     'priority' => "3",
                            //     'isTestingStage' => 0,
                            //     'icon_class_name' => "fa-shopping-cart",
                            //     'translation_code' => '',
                            //     'reference_id' => '',
                            //     'reference_table' => ''
                            // ),
                            // array(
                            //     'id' => "120",
                            //     'name' => "Usage",
                            //     'type' => "Menu",
                            //     'parent_id' => "0",
                            //     'file_path' => 'usage.php',
                            //     'priority' => "4",
                            //     'isTestingStage' => 0,
                            //     'icon_class_name' => "fa-tachometer",
                            //     'translation_code' => '',
                            //     'reference_id' => '',
                            //     'reference_table' => ''
                            // ),
                            array(
                                'id' => "160",
                                'name' => "Ticketing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => '',
                                'priority' => "4",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-ticket",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "161",
                                'name' => "Create New Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'newTicket.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "162",
                                'name' => "All Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'allTicket.php',
                                'priority' => "2",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "163",
                                'name' => "All Unassigned Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'allUnassignedTicket.php',
                                'priority' => "3",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "164",
                                'name' => "All Close Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'allCloseTicket.php',
                                'priority' => "4",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "165",
                                'name' => "My Open & Pending Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'myOpenPendingTicket.php',
                                'priority' => "5",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "166",
                                'name' => "My Close Ticket",
                                'type' => "Sub Menu",
                                'parent_id' => "160",
                                'file_path' => 'myCloseTicket.php',
                                'priority' => "6",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "130",
                                'name' => "Freeze",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'freeze.php',
                                'priority' => "5",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-user-times",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "140",
                                'name' => "Referral List",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'referralList.php',
                                'priority' => "6",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-id-badge",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "150",
                                'name' => "UTM Tracking",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'utmTracking.php',
                                'priority' => "7",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-map-marker",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "170",
                                'name' => "Verification Code Tracking",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'verificationCode.php',
                                'priority' => "8",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-mobile",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "180",
                                'name' => "News & Update",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'news.php',
                                'priority' => "9",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-newspaper-o",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "200",
                                'name' => "KYC Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'kycListing.php',
                                'priority' => "11",
                                'isTestingStage' => 0,
                                'icon_class_name' => "fa-address-card",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "210",
                                'name' => "Announcement",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => '',
                                'priority' => "11",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-file-text",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "211",
                                'name' => "Create New Announcement",
                                'type' => "Sub Menu",
                                'parent_id' => "210",
                                'file_path' => 'newAnnouncement.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "212",
                                'name' => "Schedule Announcement",
                                'type' => "Sub Menu",
                                'parent_id' => "210",
                                'file_path' => 'scheduleAnnouncement.php',
                                'priority' => "2",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "213",
                                'name' => "Sent History",
                                'type' => "Sub Menu",
                                'parent_id' => "210",
                                'file_path' => 'announcementHistory.php',
                                'priority' => "3",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            //     array(
                            //     'id' => "220",
                            //     'name' => "Blast Message",
                            //     'type' => "Menu",
                            //     'parent_id' => "0",
                            //     'file_path' => '',
                            //     'priority' => "11",
                            //     'isTesting' => 0,
                            //     'icon_class_name' => "fa-comments",
                            //     'translation_code' => '',
                            //     'reference_id' => '',
                            //     'reference_table' => ''
                            // ),
                            array(
                                'id' => "221",
                                'name' => "Create Blast Message",
                                'type' => "Sub Menu",
                                'parent_id' => "220",
                                'file_path' => 'newBlastMessage.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "222",
                                'name' => "Schedule Blast Message",
                                'type' => "Sub Menu",
                                'parent_id' => "220",
                                'file_path' => 'scheduleBlastMessage.php',
                                'priority' => "2",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "223",
                                'name' => "Sent History",
                                'type' => "Sub Menu",
                                'parent_id' => "220",
                                'file_path' => 'blastMessageHistory.php',
                                'priority' => "3",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "230",
                                'name' => "Audience Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'audienceListing.php',
                                'priority' => "11",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-user",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "239",
                                'name' => "Blog",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => '',
                                'priority' => "9",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-file-text",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "237",
                                'name' => "Article",
                                'type' => "Sub Menu",
                                'parent_id' => "239",
                                'file_path' => 'blogArticle.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "236",
                                'name' => "Video",
                                'type' => "Sub Menu",
                                'parent_id' => "239",
                                'file_path' => 'blogVideo.php',
                                'priority' => "2",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "240",
                                'name' => "Escrow Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'escrowDisputeListing.php',
                                'priority' => "11",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-address-card-o",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "250",
                                'name' => "Commission Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'adminCommissionListing.php',
                                'priority' => "11",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-address-card-o",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "260",
                                'name' => "Crowdfunding",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'crowdFundListing.php',
                                'priority' => "11",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-university",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            //  array(
                            //     'id' => "261",
                            //     'name' => "nuxStory",
                            //     'type' => "Menu",
                            //     'parent_id' => "0",
                            //     'file_path' => '',
                            //     'priority' => "9",
                            //     'isTesting' => 0,
                            //     'icon_class_name' => "fa-file-text",
                            //     'translation_code' => '',
                            //     'reference_id' => '',
                            //     'reference_table' => ''
                            // ),
                            array(
                                'id' => "263",
                                'name' => "Create Story",
                                'type' => "Sub Menu",
                                'parent_id' => "261",
                                'file_path' => 'adminCreateStory.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "262",
                                'name' => "Story Listing",
                                'type' => "Sub Menu",
                                'parent_id' => "261",
                                'file_path' => 'adminGetStoryListing.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "264",
                                'name' => "Story User Listing",
                                'type' => "Sub Menu",
                                'parent_id' => "261",
                                'file_path' => 'nuxStoryUserListing.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "265",
                                'name' => "Story Transaction Listing",
                                'type' => "Sub Menu",
                                'parent_id' => "261",
                                'file_path' => 'nuxStoryTransactionListing.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "266",
                                'name' => "Story Comment Listing",
                                'type' => "Sub Menu",
                                'parent_id' => "261",
                                'file_path' => 'nuxStoryCommentListing.php',
                                'priority' => "1",
                                'isTestingStage' => 0,
                                'icon_class_name' => "",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "267",
                                'name' => "Mobile Submit Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'mobileSubmitListing.php',
                                'priority' => "9",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-file-text",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "268",
                                'name' => "User Top Up Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'cashPoolTopUpListing.php',
                                'priority' => "9",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-user",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            ),
                            array(
                                'id' => "269",
                                'name' => "Export Excel Listing",
                                'type' => "Menu",
                                'parent_id' => "0",
                                'file_path' => 'exportExcelListing.php',
                                'priority' => "9",
                                'isTesting' => 0,
                                'icon_class_name' => "fa-file-text",
                                'translation_code' => '',
                                'reference_id' => '',
                                'reference_table' => ''
                            )


                        ),


    'pages' => array(
                        array(
                        'id' => '91',
                        'name' => 'Business General',
                        'description' => 'Business general',
                        'type' => 'Page',
                        'parent_id' => '90',
                        'file_path' => 'businessesGeneral.php',
                        'priority' => '1',
                        'icon_class_name' => '',
                        'translation_code' => '',
                        'disabled' => '0',
                        'site' => 'Admin',
                        'created_at' => '2018-03-19 00:47:42',
                        'updated_at' => '2018-03-19 00:47:42',
                        'reference_table' => '',
                        'reference_id' => ''
                        ),
                        array(
                            'id' => '92',
                            'name' => 'Business Usage',
                            'description' => 'Business usage',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesUsage.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '93',
                            'name' => 'Business Puchase History',
                            'description' => 'Business Puchase History',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesTopUpHistory.php',
                            'priority' => '3',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '101',
                            'name' => 'Invoice',
                            'description' => 'Invoice',
                            'type' => 'Page',
                            'parent_id' => '93',
                            'file_path' => 'invoice.php',
                            'priority' => '11',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '94',
                            'name' => 'Business Categories',
                            'description' => 'Business Categories',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesCategories.php',
                            'priority' => '4',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '95',
                            'name' => 'Business Team Member',
                            'description' => 'Business Team Member',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesTeamMember.php',
                            'priority' => '5',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '96',
                            'name' => 'Business Followers',
                            'description' => 'Business Followers',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesFollower.php',
                            'priority' => '6',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '97',
                            'name' => 'Add Business Category',
                            'description' => 'Add business category',
                            'type' => 'Page',
                            'parent_id' => '94',
                            'file_path' => 'businessesAddCategories.php',
                            'priority' => '7',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '98',
                            'name' => 'Edit Business Category',
                            'description' => 'Edit business category',
                            'type' => 'Page',
                            'parent_id' => '94',
                            'file_path' => 'businessesEditCategories.php',
                            'priority' => '8',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '99',
                            'name' => 'Add Business Team Member',
                            'description' => 'Add Business Team Member',
                            'type' => 'Page',
                            'parent_id' => '95',
                            'file_path' => 'businessesAddTeamMember.php',
                            'priority' => '9',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '100',
                            'name' => 'Edit Business Team Member',
                            'description' => 'Edit Business Team Member',
                            'type' => 'Page',
                            'parent_id' => '95',
                            'file_path' => 'businessesEditTeamMember.php',
                            'priority' => '10',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '101',
                            'name' => 'Business Live Chat Settings',
                            'description' => 'Business Live Chat Settings',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesLiveChatSettings.php',
                            'priority' => '11',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '102',
                            'name' => 'Business Commission Listing',
                            'description' => 'Business Commission Listing',
                            'type' => 'Page',
                            'parent_id' => '90',
                            'file_path' => 'businessesCommissionListing.php',
                            'priority' => '11',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '103',
                            'name' => 'Business Commission Details',
                            'description' => 'Business Commission Details',
                            'type' => 'Page',
                            'parent_id' => '102',
                            'file_path' => 'businessesCommissionListingDetails.php',
                            'priority' => '11',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '111',
                            'name' => 'Invoice',
                            'description' => 'Invoice',
                            'type' => 'Page',
                            'parent_id' => '110',
                            'file_path' => 'invoice.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '167',
                            'name' => 'Ticket Info',
                            'description' => 'Ticket Info',
                            'type' => 'Page',
                            'parent_id' => '162',
                            'file_path' => 'ticketInfo.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '168',
                            'name' => 'Ticket Inbox',
                            'description' => 'Ticket Inbox',
                            'type' => 'Page',
                            'parent_id' => '162',
                            'file_path' => 'ticketInbox.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '151',
                            'name' => 'Individual Tracking',
                            'description' => 'Individual Tracking',
                            'type' => 'Page',
                            'parent_id' => '',
                            'file_path' => 'utmIndividual.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '181',
                            'name' => 'New Blog',
                            'description' => 'New Blog',
                            'type' => 'Page',
                            'parent_id' => '180',
                            'file_path' => 'newBlog.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '214',
                            'name' => 'Edit Announcement',
                            'description' => 'Edit Announcement',
                            'type' => 'Page',
                            'parent_id' => '210',
                            'file_path' => 'editAnnouncement.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '215',
                            'name' => 'Announcement History Details',
                            'description' => 'Announcement History Details',
                            'type' => 'Page',
                            'parent_id' => '210',
                            'file_path' => 'announcementHistoryDetails.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '216',
                            'name' => 'Recipient Listing',
                            'description' => 'Recipient Listing',
                            'type' => 'Page',
                            'parent_id' => '210',
                            'file_path' => 'announcementRecipientListing.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '224',
                            'name' => 'Edit Blast Message',
                            'description' => 'Edit Blast Message',
                            'type' => 'Page',
                            'parent_id' => '220',
                            'file_path' => 'editBlastMessage.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '225',
                            'name' => 'Blast Message History Details',
                            'description' => 'Blast Message History Details',
                            'type' => 'Page',
                            'parent_id' => '220',
                            'file_path' => 'blastMessageHistoryDetails.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '226',
                            'name' => 'Recipient Listing',
                            'description' => 'Recipient Listing',
                            'type' => 'Page',
                            'parent_id' => '220',
                            'file_path' => 'blastMessageRecipientListing.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '232',
                            'name' => 'Edit Audience',
                            'description' => 'Edit Audience',
                            'type' => 'Page',
                            'parent_id' => '230',
                            'file_path' => 'editAudience.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                         array(
                            'id' => '233',
                            'name' => 'View Audience',
                            'description' => 'View Audience',
                            'type' => 'Page',
                            'parent_id' => '230',
                            'file_path' => 'viewAudience.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '182',
                            'name' => 'Edit Blog',
                            'description' => 'Edit Blog',
                            'type' => 'Page',
                            'parent_id' => '180',
                            'file_path' => 'editBlog.php',
                            'priority' => '2',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '234',
                            'name' => 'New Article',
                            'description' => 'New Article',
                            'type' => 'Page',
                            'parent_id' => '237',
                            'file_path' => 'newArticle.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '235',
                            'name' => 'New Video',
                            'description' => 'New Video',
                            'type' => 'Page',
                            'parent_id' => '236',
                            'file_path' => 'newVideo.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '2018-03-19 00:47:42',
                            'updated_at' => '2018-03-19 00:47:42',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '241',
                            'name' => 'Escrow Info',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '240',
                            'file_path' => 'escrowDisputeInfo.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '242',
                            'name' => 'Escrow Inbox',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '240',
                            'file_path' => 'escrowDisputeInbox.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '242',
                            'name' => 'Escrow Inbox',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '240',
                            'file_path' => 'escrowDisputeInbox.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '251',
                            'name' => 'Commission Details',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '250',
                            'file_path' => 'adminCommissionListingDetails.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '252',
                            'name' => 'Story Details',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '262',
                            'file_path' => 'storyListingDetails.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '253',
                            'name' => 'Story Update',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '262',
                            'file_path' => 'storyListingUpdate.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '254',
                            'name' => 'Story Transactions',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '262',
                            'file_path' => 'storyListingTransaction.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '255',
                            'name' => 'Story Activity',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '262',
                            'file_path' => 'storyListingActivity.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '256',
                            'name' => 'Fund Details',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '263',
                            'file_path' => 'adminCreateFundDetails.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '257',
                            'name' => 'Post Preview',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '263',
                            'file_path' => 'adminCreateStoryPreview.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        ),
                        array(
                            'id' => '258',
                            'name' => 'Story Comment',
                            'description' => '',
                            'type' => 'Page',
                            'parent_id' => '262',
                            'file_path' => 'storyListingComment.php',
                            'priority' => '1',
                            'icon_class_name' => '',
                            'translation_code' => '',
                            'disabled' => '0',
                            'site' => 'Admin',
                            'created_at' => '',
                            'updated_at' => '',
                            'reference_table' => '',
                            'reference_id' => ''
                        )

                    )

    );

?>
