   <option value=""><?php echo $translations["M00638"][$language]; /* Select a country */ ?></option>
   <option value="Afghanistan"><?php echo $translations["M00639"][$language]; /* Afghanistan */ ?></option>
   <option value="Aland Islands"><?php echo $translations["M00640"][$language]; /* Aland Islands */ ?></option>
   <option value="Albania"><?php echo $translations["M00641"][$language]; /* Albania */ ?></option>
   <option value="Algeria"><?php echo $translations["M00642"][$language]; /* Algeria */ ?></option>
   <option value="American Samoa"><?php echo $translations["M00643"][$language]; /* American Samoa */ ?></option>
   <option value="Andorra"><?php echo $translations["M00644"][$language]; /* Andorra */ ?></option>
   <option value="Angola"><?php echo $translations["M00645"][$language]; /* Angola */ ?></option>
   <option value="Anguilla"><?php echo $translations["M00646"][$language]; /* Anguilla */ ?></option>
   <option value="Antarctica"><?php echo $translations["M00647"][$language]; /* Antarctica */ ?></option>
   <option value="Antigua and Barbuda"><?php echo $translations["M00648"][$language]; /* Antigua and Barbuda */ ?></option>
   <option value="Argentina"><?php echo $translations["M00649"][$language]; /* Argentina */ ?></option>
   <option value="Armenia"><?php echo $translations["M00650"][$language]; /* Armenia */ ?></option>
   <option value="Aruba"><?php echo $translations["M00651"][$language]; /* Aruba */ ?></option>
   <option value="Australia"><?php echo $translations["M00652"][$language]; /* Australia */ ?></option>
   <option value="Austria"><?php echo $translations["M00653"][$language]; /* Austria */ ?></option>
   <option value="Azerbaijan"><?php echo $translations["M00654"][$language]; /* Azerbaijan */ ?></option>
   <option value="Bahamas"><?php echo $translations["M00655"][$language]; /* Bahamas */ ?></option>
   <option value="Bahrain"><?php echo $translations["M00656"][$language]; /* Bahrain */ ?></option>
   <option value="Bangladesh"><?php echo $translations["M00657"][$language]; /* Bangladesh */ ?></option>
   <option value="Barbados"><?php echo $translations["M00658"][$language]; /* Barbados */ ?></option>
   <option value="Belarus"><?php echo $translations["M00659"][$language]; /* Belarus */ ?></option>
   <option value="Belgium"><?php echo $translations["M00660"][$language]; /* Belgium */ ?></option>
   <option value="Belize"><?php echo $translations["M00661"][$language]; /* Belize */ ?></option>
   <option value="Benin"><?php echo $translations["M00662"][$language]; /* Benin */ ?></option>
   <option value="Bermuda"><?php echo $translations["M00663"][$language]; /* Bermuda */ ?></option>
   <option value="Bhutan"><?php echo $translations["M00664"][$language]; /* Bhutan */ ?></option>
   <option value="Bolivia, Plurinational State of"><?php echo $translations["M00665"][$language]; /* Bolivia, Plurinational State of */ ?></option>
   <option value="Bosnia and Herzegovina"><?php echo $translations["M00666"][$language]; /* Bosnia and Herzegovina */ ?></option>
   <option value="Botswana"><?php echo $translations["M00667"][$language]; /* Botswana */ ?></option>
   <option value="Bouvet Island"><?php echo $translations["M00668"][$language]; /* Bouvet Island */ ?></option>
   <option value="Brazil"><?php echo $translations["M00669"][$language]; /* Brazil */ ?></option>
   <option value="British Indian Ocean Territory"><?php echo $translations["M00670"][$language]; /* British Indian Ocean Territory */ ?></option>
   <option value="Brunei Darussalam"><?php echo $translations["M00671"][$language]; /* Brunei Darussalam */ ?></option>
   <option value="Bulgaria"><?php echo $translations["M00672"][$language]; /* Bulgaria */ ?></option>
   <option value="Burkina Faso"><?php echo $translations["M00673"][$language]; /* Burkina Faso */ ?></option>
   <option value="Burundi"><?php echo $translations["M00674"][$language]; /* Burundi */ ?></option>
   <option value="Cambodia"><?php echo $translations["M00675"][$language]; /* Cambodia */ ?></option>
   <option value="Cameroon"><?php echo $translations["M00676"][$language]; /* Cameroon */ ?></option>
   <option value="Canada"><?php echo $translations["M00677"][$language]; /* Canada */ ?></option>
   <option value="Cape Verde"><?php echo $translations["M00678"][$language]; /* Cape Verde */ ?></option>
   <option value="Cayman Islands"><?php echo $translations["M00679"][$language]; /* Cayman Islands */ ?></option>
   <option value="Central African Republic"><?php echo $translations["M00680"][$language]; /* Central African Republic */ ?></option>
   <option value="Chad"><?php echo $translations["M00681"][$language]; /* Chad */ ?></option>
   <option value="Chile"><?php echo $translations["M00682"][$language]; /* Chile */ ?></option>
   
   <option value="Christmas Island"><?php echo $translations["M00684"][$language]; /* Christmas Island */ ?></option>
   <option value="Cocos (Keeling) Islands"><?php echo $translations["M00685"][$language]; /* Cocos (Keeling) Islands */ ?></option>
   <option value="Colombia"><?php echo $translations["M00686"][$language]; /* Colombia */ ?></option>
   <option value="Comoros"><?php echo $translations["M00687"][$language]; /* Comoros */ ?></option>
   <option value="Congo"><?php echo $translations["M00688"][$language]; /* Congo */ ?></option>
   <option value="Congo, The Democratic Republic of the"><?php echo $translations["M00689"][$language]; /* Congo, The Democratic Republic of the */ ?></option>
   <option value="Cook Islands"><?php echo $translations["M00690"][$language]; /* Cook Islands */ ?></option>
   <option value="Costa Rica"><?php echo $translations["M00691"][$language]; /* Costa Rica */ ?></option>
   <option value="Cote d'Ivoire"><?php echo $translations["M00692"][$language]; /* Cote d'Ivoire */ ?></option>
   <option value="Croatia"><?php echo $translations["M00693"][$language]; /* Croatia */ ?></option>
   <option value="Cuba"><?php echo $translations["M00694"][$language]; /* Cuba */ ?></option>
   <option value="Curacao"><?php echo $translations["M00695"][$language]; /* Curacao */ ?></option>
   <option value="Cyprus"><?php echo $translations["M00696"][$language]; /* Cyprus */ ?></option>
   <option value="Czech Republic"><?php echo $translations["M00697"][$language]; /* Czech Republic */ ?></option>
   <option value="Denmark"><?php echo $translations["M00698"][$language]; /* Denmark */ ?></option>
   <option value="Djibouti"><?php echo $translations["M00699"][$language]; /* Djibouti */ ?></option>
   <option value="Dominica"><?php echo $translations["M00700"][$language]; /* Dominica */ ?></option>
   <option value="Dominican Republic"><?php echo $translations["M00701"][$language]; /* Dominican Republic */ ?></option>
   <option value="Ecuador"><?php echo $translations["M00702"][$language]; /* Ecuador */ ?></option>
   <option value="Egypt"><?php echo $translations["M00703"][$language]; /* Egypt */ ?></option>
   <option value="El Salvador"><?php echo $translations["M00704"][$language]; /* El Salvador */ ?></option>
   <option value="Equatorial Guinea"><?php echo $translations["M00705"][$language]; /* Equatorial Guinea */ ?></option>
   <option value="Eritrea"><?php echo $translations["M00706"][$language]; /* Eritrea */ ?></option>
   <option value="Estonia"><?php echo $translations["M00707"][$language]; /* Estonia */ ?></option>
   <option value="Ethiopia"><?php echo $translations["M00708"][$language]; /* Ethiopia */ ?></option>
   <option value="Falkland Islands (Malvinas)"><?php echo $translations["M00709"][$language]; /* Falkland Islands (Malvinas) */ ?></option>
   <option value="Faroe Islands"><?php echo $translations["M00710"][$language]; /* Faroe Islands */ ?></option>
   <option value="Fiji"><?php echo $translations["M00711"][$language]; /* Fiji */ ?></option>
   <option value="Finland"><?php echo $translations["M00712"][$language]; /* Finland */ ?></option>
   <option value="France"><?php echo $translations["M00713"][$language]; /* France */ ?></option>
   <option value="French Guiana"><?php echo $translations["M00714"][$language]; /* French Guiana */ ?></option>
   <option value="French Polynesia"><?php echo $translations["M00715"][$language]; /* French Polynesia */ ?></option>
   <option value="French Southern Territories"><?php echo $translations["M00716"][$language]; /* French Southern Territories */ ?></option>
   <option value="Gabon"><?php echo $translations["M00717"][$language]; /* Gabon */ ?></option>
   <option value="Gambia"><?php echo $translations["M00718"][$language]; /* Gambia */ ?></option>
   <option value="Georgia"><?php echo $translations["M00719"][$language]; /* Georgia */ ?></option>
   <option value="Germany"><?php echo $translations["M00720"][$language]; /* Germany */ ?></option>
   <option value="Ghana"><?php echo $translations["M00721"][$language]; /* Ghana */ ?></option>
   <option value="Gibraltar"><?php echo $translations["M00722"][$language]; /* Gibraltar */ ?></option>
   <option value="Greece"><?php echo $translations["M00723"][$language]; /* Greece */ ?></option>
   <option value="Greenland"><?php echo $translations["M00724"][$language]; /* Greenland */ ?></option>
   <option value="Grenada"><?php echo $translations["M00725"][$language]; /* Grenada */ ?></option>
   <option value="Guadeloupe"><?php echo $translations["M00726"][$language]; /* Guadeloupe */ ?></option>
   <option value="Guam"><?php echo $translations["M00727"][$language]; /* Guam */ ?></option>
   <option value="Guatemala"><?php echo $translations["M00728"][$language]; /* Guatemala */ ?></option>
   <option value="Guernsey"><?php echo $translations["M00729"][$language]; /* Guernsey */ ?></option>
   <option value="Guinea"><?php echo $translations["M00730"][$language]; /* Guinea */ ?></option>
   <option value="Guinea-Bissau"><?php echo $translations["M00731"][$language]; /* Guinea-Bissau */ ?></option>
   <option value="Guyana"><?php echo $translations["M00732"][$language]; /* Guyana */ ?></option>
   <option value="Haiti"><?php echo $translations["M00733"][$language]; /* Haiti */ ?></option>
   <option value="Heard Island and McDonald Islands"><?php echo $translations["M00734"][$language]; /* Heard Island and McDonald Islands */ ?></option>
   <option value="Holy See (Vatican City State)"><?php echo $translations["M00735"][$language]; /* Holy See (Vatican City State) */ ?></option>
   <option value="Honduras"><?php echo $translations["M00736"][$language]; /* Honduras */ ?></option>
   <option value="Hong Kong"><?php echo $translations["M00737"][$language]; /* Hong Kong */ ?></option>
   <option value="Hungary"><?php echo $translations["M00738"][$language]; /* Hungary */ ?></option>
   <option value="Iceland"><?php echo $translations["M00739"][$language]; /* Iceland */ ?></option>
   <option value="India"><?php echo $translations["M00740"][$language]; /* India */ ?></option>
   <option value="Indonesia"><?php echo $translations["M00741"][$language]; /* Indonesia */ ?></option>
   <option value="Iran, Islamic Republic of"><?php echo $translations["M00742"][$language]; /* Iran, Islamic Republic of */ ?></option>
   <option value="Iraq"><?php echo $translations["M00743"][$language]; /* Iraq */ ?></option>
   <option value="Ireland"><?php echo $translations["M00744"][$language]; /* Ireland */ ?></option>
   <option value="Isle of Man"><?php echo $translations["M00745"][$language]; /* Isle of Man */ ?></option>
   <option value="Israel"><?php echo $translations["M00746"][$language]; /* Israel */ ?></option>
   <option value="Italy"><?php echo $translations["M00747"][$language]; /* Italy */ ?></option>
   <option value="Jamaica"><?php echo $translations["M00748"][$language]; /* Jamaica */ ?></option>
   <option value="Japan"><?php echo $translations["M00749"][$language]; /* Japan */ ?></option>
   <option value="Jordan"><?php echo $translations["M00750"][$language]; /* Jordan */ ?></option>
   <option value="Kazakhstan"><?php echo $translations["M00751"][$language]; /* Kazakhstan */ ?></option>
   <option value="Kenya"><?php echo $translations["M00752"][$language]; /* Kenya */ ?></option>
   <option value="Kiribati"><?php echo $translations["M00753"][$language]; /* Kiribati */ ?></option>
   <option value="Korea, Democratic People's Republic of (North Korea)"><?php echo $translations["M00754"][$language]; /* Korea, Democratic People's Republic of (North Korea) */ ?></option>
   <option value="Korea, Republic of (South Korea)"><?php echo $translations["M00755"][$language]; /* Korea, Republic of (South Korea) */ ?></option>
   <option value="Kuwait"><?php echo $translations["M00756"][$language]; /* Kuwait */ ?></option>
   <option value="Kyrgyzstan"><?php echo $translations["M00757"][$language]; /* Kyrgyzstan */ ?></option>
   <option value="Lao People's Democratic Republic"><?php echo $translations["M00758"][$language]; /* Lao People's Democratic Republic */ ?></option>
   <option value="Latvia"><?php echo $translations["M00759"][$language]; /* Latvia */ ?></option>
   <option value="Lebanon"><?php echo $translations["M00760"][$language]; /* Lebanon */ ?></option>
   <option value="Lesotho"><?php echo $translations["M00761"][$language]; /* Lesotho */ ?></option>
   <option value="Liberia"><?php echo $translations["M00762"][$language]; /* Liberia */ ?></option>
   <option value="Libyan Arab Jamahiriya"><?php echo $translations["M00763"][$language]; /* Libyan Arab Jamahiriya */ ?></option>
   <option value="Liechtenstein"><?php echo $translations["M00764"][$language]; /* Liechtenstein */ ?></option>
   <option value="Lithuania"><?php echo $translations["M00765"][$language]; /* Lithuania */ ?></option>
   <option value="Luxembourg"><?php echo $translations["M00766"][$language]; /* Luxembourg */ ?></option>
   <option value="Macao"><?php echo $translations["M00767"][$language]; /* Macao */ ?></option>
   <option value="Macedonia, The former Yugoslav Republic of"><?php echo $translations["M00768"][$language]; /* Macedonia, The former Yugoslav Republic of */ ?></option>
   <option value="Madagascar"><?php echo $translations["M00769"][$language]; /* Madagascar */ ?></option>
   <option value="Malawi"><?php echo $translations["M00770"][$language]; /* Malawi */ ?></option>
   <option value="Malaysia"><?php echo $translations["M00771"][$language]; /* Malaysia */ ?></option>
   <option value="Maldives"><?php echo $translations["M00772"][$language]; /* Maldives */ ?></option>
   <option value="Mali"><?php echo $translations["M00773"][$language]; /* Mali */ ?></option>
   <option value="Malta"><?php echo $translations["M00774"][$language]; /* Malta */ ?></option>
   <option value="Marshall Islands"><?php echo $translations["M00775"][$language]; /* Marshall Islands */ ?></option>
   <option value="Martinique"><?php echo $translations["M00776"][$language]; /* Martinique */ ?></option>
   <option value="Mauritania"><?php echo $translations["M00777"][$language]; /* Mauritania */ ?></option>
   <option value="Mauritius"><?php echo $translations["M00778"][$language]; /* Mauritius */ ?></option>
   <option value="Mayotte"><?php echo $translations["M00779"][$language]; /* Mayotte */ ?></option>
   <option value="Mexico"><?php echo $translations["M00780"][$language]; /* Mexico */ ?></option>
   <option value="Micronesia, Federated States of"><?php echo $translations["M00781"][$language]; /* Micronesia, Federated States of */ ?></option>
   <option value="Moldova, Republic of"><?php echo $translations["M00782"][$language]; /* Moldova, Republic of */ ?></option>
   <option value="Monaco"><?php echo $translations["M00783"][$language]; /* Monaco */ ?></option>
   <option value="Mongolia"><?php echo $translations["M00784"][$language]; /* Mongolia */ ?></option>
   <option value="Montenegro"><?php echo $translations["M00785"][$language]; /* Montenegro */ ?></option>
   <option value="Montserrat"><?php echo $translations["M00786"][$language]; /* Montserrat */ ?></option>
   <option value="Morocco"><?php echo $translations["M00787"][$language]; /* Morocco */ ?></option>
   <option value="Mozambique"><?php echo $translations["M00788"][$language]; /* Mozambique */ ?></option>
   <option value="Myanmar"><?php echo $translations["M00789"][$language]; /* Myanmar */ ?></option>
   <option value="Namibia"><?php echo $translations["M00790"][$language]; /* Namibia */ ?></option>
   <option value="Nauru"><?php echo $translations["M00791"][$language]; /* Nauru */ ?></option>
   <option value="Nepal"><?php echo $translations["M00792"][$language]; /* Nepal */ ?></option>
   <option value="Netherlands"><?php echo $translations["M00793"][$language]; /* Netherlands */ ?></option>
   <option value="New Caledonia"><?php echo $translations["M00794"][$language]; /* New Caledonia */ ?></option>
   <option value="New Jersey"><?php echo $translations["M00795"][$language]; /* New Jersey */ ?></option>
   <option value="New Zealand"><?php echo $translations["M00796"][$language]; /* New Zealand */ ?></option>
   <option value="Nicaragua"><?php echo $translations["M00797"][$language]; /* Nicaragua */ ?></option>
   <option value="Niger"><?php echo $translations["M00798"][$language]; /* Niger */ ?></option>
   <option value="Nigeria"><?php echo $translations["M00799"][$language]; /* Nigeria */ ?></option>
   <option value="Niue"><?php echo $translations["M00800"][$language]; /* Niue */ ?></option>
   <option value="Norfolk Island"><?php echo $translations["M00801"][$language]; /* Norfolk Island */ ?></option>
   <option value="Northern Mariana Islands"><?php echo $translations["M00802"][$language]; /* Northern Mariana Islands */ ?></option>
   <option value="Norway"><?php echo $translations["M00803"][$language]; /* Norway */ ?></option>
   <option value="Oman"><?php echo $translations["M00804"][$language]; /* Oman */ ?></option>
   <option value="Pakistan"><?php echo $translations["M00805"][$language]; /* Pakistan */ ?></option>
   <option value="Palau"><?php echo $translations["M00806"][$language]; /* Palau */ ?></option>
   <option value="Palestinian Territory, Occupied"><?php echo $translations["M00807"][$language]; /* Palestinian Territory, Occupied */ ?></option>
   <option value="Panama"><?php echo $translations["M00808"][$language]; /* Panama */ ?></option>
   <option value="Papua New Guinea"><?php echo $translations["M00809"][$language]; /* Papua New Guinea */ ?></option>
   <option value="Paraguay"><?php echo $translations["M00810"][$language]; /* Paraguay */ ?></option>
   <option value="Peru"><?php echo $translations["M00811"][$language]; /* Peru */ ?></option>
   <option value="Philippines"><?php echo $translations["M00812"][$language]; /* Philippines */ ?></option>
   <option value="Pitcairn"><?php echo $translations["M00813"][$language]; /* Pitcairn */ ?></option>
   <option value="Poland"><?php echo $translations["M00814"][$language]; /* Poland */ ?></option>
   <option value="Portugal"><?php echo $translations["M00815"][$language]; /* Portugal */ ?></option>
   <option value="Puerto Rico"><?php echo $translations["M00816"][$language]; /* Puerto Rico */ ?></option>
   <option value="Qatar"><?php echo $translations["M00817"][$language]; /* Qatar */ ?></option>
   <option value="Reunion"><?php echo $translations["M00818"][$language]; /* Reunion */ ?></option>
   <option value="Romania"><?php echo $translations["M00819"][$language]; /* Romania */ ?></option>
   <option value="Russian Federation"><?php echo $translations["M00820"][$language]; /* Russian Federation */ ?></option>
   <option value="Rwanda"><?php echo $translations["M00821"][$language]; /* Rwanda */ ?></option>
   <option value="Saint Barthelemy"><?php echo $translations["M00822"][$language]; /* Saint Barthelemy */ ?></option>
   <option value="Saint Helena, Ascension and Tristan Da Cunha"><?php echo $translations["M00823"][$language]; /* Saint Helena, Ascension and Tristan Da Cunha */ ?></option>
   <option value="Saint Kitts and Nevis"><?php echo $translations["M00824"][$language]; /* Saint Kitts and Nevis */ ?></option>
   <option value="Saint Lucia"><?php echo $translations["M00825"][$language]; /* Saint Lucia */ ?></option>
   <option value="Saint Martin (French Part)"><?php echo $translations["M00826"][$language]; /* Saint Martin (French Part */ ?>)</option>
   <option value="Saint Pierre and Miquelon"><?php echo $translations["M00827"][$language]; /* Saint Pierre and Miquelon */ ?></option>
   <option value="Saint Vincent and The Grenadines"><?php echo $translations["M00828"][$language]; /* Saint Vincent and The Grenadines */ ?></option>
   <option value="Samoa"><?php echo $translations["M00829"][$language]; /* Samoa */ ?></option>
   <option value="San Marino"><?php echo $translations["M00830"][$language]; /* San Marino */ ?></option>
   <option value="Sao Tome and Principe"><?php echo $translations["M00831"][$language]; /* Sao Tome and Principe */ ?></option>
   <option value="Saudi Arabia"><?php echo $translations["M00832"][$language]; /* Saudi Arabia */ ?></option>
   <option value="Senegal"><?php echo $translations["M00833"][$language]; /* Senegal */ ?></option>
   <option value="Serbia"><?php echo $translations["M00834"][$language]; /* Serbia */ ?></option>
   <option value="Seychelles"><?php echo $translations["M00835"][$language]; /* Seychelles */ ?></option>
   <option value="Sierra Leone"><?php echo $translations["M00836"][$language]; /* Sierra Leone */ ?></option>
   <option value="Singapore"><?php echo $translations["M00837"][$language]; /* Singapore */ ?></option>
   <option value="Sint Maarten (Dutch Part)"><?php echo $translations["M00838"][$language]; /* Sint Maarten (Dutch Part) */ ?></option>
   <option value="Slovakia"><?php echo $translations["M00839"][$language]; /* Slovakia */ ?></option>
   <option value="Slovenia"><?php echo $translations["M00840"][$language]; /* Slovenia */ ?></option>
   <option value="Solomon Islands"><?php echo $translations["M00841"][$language]; /* Solomon Islands */ ?></option>
   <option value="Somalia"><?php echo $translations["M00842"][$language]; /* Somalia */ ?></option>
   <option value="South Africa"><?php echo $translations["M00843"][$language]; /* South Africa */ ?></option>
   <option value="South Georgia and The South Sandwich Islands"><?php echo $translations["M00844"][$language]; /* South Georgia and The South Sandwich Islands */ ?></option>
   <option value="South Sudan"><?php echo $translations["M00845"][$language]; /* South Sudan */ ?></option>
   <option value="Spain"><?php echo $translations["M00846"][$language]; /* Spain */ ?></option>
   <option value="Sri Lanka"><?php echo $translations["M00847"][$language]; /* Sri Lanka */ ?></option>
   <option value="Sudan"><?php echo $translations["M00848"][$language]; /* Sudan */ ?></option>
   <option value="Suriname"><?php echo $translations["M00849"][$language]; /* Suriname */ ?></option>
   <option value="Svalbard and Jan Mayen"><?php echo $translations["M00850"][$language]; /* Svalbard and Jan Mayen */ ?></option>
   <option value="Swaziland"><?php echo $translations["M00851"][$language]; /* Swaziland */ ?></option>
   <option value="Sweden"><?php echo $translations["M00852"][$language]; /* Sweden */ ?></option>
   <option value="Switzerland"><?php echo $translations["M00853"][$language]; /* Switzerland */ ?></option>
   <option value="Syrian Arab Republic"><?php echo $translations["M00854"][$language]; /* Syrian Arab Republic */ ?></option>
   <option value="Taiwan"><?php echo $translations["M00855"][$language]; /* Taiwan */ ?></option>
   <option value="Tajikistan"><?php echo $translations["M00856"][$language]; /* Tajikistan */ ?></option>
   <option value="Tanzania, United Republic of"><?php echo $translations["M00857"][$language]; /* Tanzania, United Republic of */ ?></option>
   <option value="Thailand"><?php echo $translations["M00858"][$language]; /* Thailand */ ?></option>
   <option value="Timor-Leste"><?php echo $translations["M00859"][$language]; /* Timor-Leste */ ?></option>
   <option value="Togo"><?php echo $translations["M00860"][$language]; /* Togo */ ?></option>
   <option value="Tokelau"><?php echo $translations["M00861"][$language]; /* Tokelau */ ?></option>
   <option value="Tonga"><?php echo $translations["M00862"][$language]; /* Tonga */ ?></option>
   <option value="Trinidad and Tobago"><?php echo $translations["M00863"][$language]; /* Trinidad and Tobago */ ?></option>
   <option value="Tunisia"><?php echo $translations["M00864"][$language]; /* Tunisia */ ?></option>
   <option value="Turkey"><?php echo $translations["M00865"][$language]; /* Turkey */ ?></option>
   <option value="Turkmenistan"><?php echo $translations["M00866"][$language]; /* Turkmenistan */ ?></option>
   <option value="Turks and Caicos Islands"><?php echo $translations["M00867"][$language]; /* Turks and Caicos Islands */ ?></option>
   <option value="Tuvalu"><?php echo $translations["M00868"][$language]; /* Tuvalu */ ?></option>
   <option value="Uganda"><?php echo $translations["M00869"][$language]; /* Uganda */ ?></option>
   <option value="Ukraine"><?php echo $translations["M00870"][$language]; /* Ukraine */ ?></option>
   <option value="United Arab Emirates"><?php echo $translations["M00871"][$language]; /* United Arab Emirates */ ?></option>
   <option value="United Kingdom"><?php echo $translations["M00872"][$language]; /* United Kingdom */ ?></option>
   <option value="United States"><?php echo $translations["M00873"][$language]; /* United States */ ?></option>
   <option value="United States Minor Outlying Islands"><?php echo $translations["M00874"][$language]; /* Malawi */ ?></option>
   <option value="Uruguay"><?php echo $translations["M00875"][$language]; /* Uruguay */ ?></option>
   <option value="Uzbekistan"><?php echo $translations["M00876"][$language]; /* Uzbekistan */ ?></option>
   <option value="Vanuatu"><?php echo $translations["M00877"][$language]; /* Vanuatu */ ?></option>
   <option value="Venezuela, Bolivarian Republic of"><?php echo $translations["M00878"][$language]; /* Venezuela, Bolivarian Republic of */ ?></option>
   <option value="Vietnam"><?php echo $translations["M00879"][$language]; /* Vietnam */ ?></option>
   <option value="Virgin Islands, British"><?php echo $translations["M00880"][$language]; /* Virgin Islands, British */ ?></option>
   <option value="Virgin Islands, U.S."><?php echo $translations["M00881"][$language]; /* Virgin Islands, U.S. */ ?></option>
   <option value="Wallis and Futuna"><?php echo $translations["M00882"][$language]; /* MaWallis and Futunalawi */ ?></option>
   <option value="Western Sahara"><?php echo $translations["M00883"][$language]; /* Western Sahara */ ?></option>
   <option value="Yemen"><?php echo $translations["M00884"][$language]; /* Yemen */ ?></option>
   <option value="Zambia"><?php echo $translations["M00885"][$language]; /* Zambia */ ?></option>
   <option value="Zimbabwe"><?php echo $translations["M00886"][$language]; /* Zimbabwe */ ?></option>
